#!/bin/bash

TOKEN=`cat /usr/secure/.token`

echo "Start create VM"

# REPO="mister5111/api-service"

# curl -X POST \
#   -H "Accept: application/vnd.github.v3+json" \
#   -H "Authorization: token $TOKEN" \
#   https://api.github.com/repos/$REPO/actions/workflows/deploy.yml/dispatches \
#   -d '{"ref":"main"}'

# sleep 2

# ID=`curl -s -H "Authorization: token $TOKEN" \
#   "https://api.github.com/repos/$REPO/actions/workflows/deploy.yml/runs" | jq -r '.workflow_runs[0].id'`

# while true; do
#     STATUS=$(curl -s -H "Authorization: token $TOKEN" \
#         "https://api.github.com/repos/$REPO/actions/runs/$ID" | jq '{status}')

#     S=`echo "$STATUS" | jq -r '.status'`
#     echo "Create status: $S wait ."
#     sleep 0.5
#     echo "Create status: $S wait .."
#     sleep 0.5
#     echo "Create status: $S wait ..."
#     sleep 0.5
#     echo "Create status: $S wait ...."
#     sleep 0.5

#     if [ "$S" = "completed" ]; then
#         sleep 2
#         break
#     fi

# done

sleep 2

# IP=`curl -s -X GET "https://api.github.com/repos/$REPO/actions/variables/IP_INSTANCES" \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: token $TOKEN" \
#   -H "X-GitHub-Api-Version: 2022-11-28" | jq -r '.value'`

# echo "$IP"

TIMER=300
while [ $TIMER -gt 0 ]; do
    MIN=$((TIMER / 60))
    SEC=$((TIMER % 60))
    echo -e "Remaining Time: $MIN min $SEC sec\nTest"
    sleep 1
    ((TIMER--))
done

echo "Run Destroy"

sleep 2

# curl -X POST \
#   -H "Accept: application/vnd.github.v3+json" \
#   -H "Authorization: token $TOKEN" \
#   https://api.github.com/repos/$REPO/actions/workflows/destroy.yml/dispatches \
#   -d '{"ref":"main"}'

# sleep 2

# ID=`curl -s -H "Authorization: token $TOKEN" \
#   "https://api.github.com/repos/$REPO/actions/workflows/destroy.yml/runs" | jq -r '.workflow_runs[0].id'`

# while true; do
#     STATUS=$(curl -s -H "Authorization: token $TOKEN" \
#         "https://api.github.com/repos/$REPO/actions/runs/$ID" | jq '{status}')

#     S=`echo "$STATUS" | jq -r '.status'`
#     echo "Destroy status: $S"

#     if [ "$S" = "completed" ]; then
#         sleep 2
#         break
#     fi

#     sleep 2
# done
