name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v1

      - name: Create ZIP
        run: |
            tar --exclude='.git' --exclude='conf' -cvf visit-card.tar .
            tar -cvf nginx-conf.tar conf/nginx/visit-card.conf conf/nginx/nginx.conf
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy

      - name: Copy project
        run: | 
            scp -i ~/.ssh/deploy -o 'StrictHostKeyChecking no' visit-card.tar nginx-conf.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/deploy/

      - name: Deploy to server
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/deploy ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          sudo -s
          mkdir /var/www/visit-card
          apt install nginx php8.2-fpm -y
          systemctl enable php8.2-fpm
          rm /etc/nginx/sites-enabled/default
          rm /etc/nginx/sites-available/default
          tar -xvf visit-card.tar -C /var/www/visit-card --overwrite
          tar -xvf nginx-conf.tar -C /usr/src/ --overwrite
          cp -r /usr/src/conf/nginx/visit-card.conf /etc/nginx/sites-enabled/
          cp -r /usr/src/conf/nginx/visit-card.conf /etc/nginx/sites-available/
          cp -r /usr/src/conf/nginx/nginx.conf /etc/nginx/
          chmod +x /var/www/visit-card/script/run_vm
          systemctl restart nginx
          ENDSSH

      - name: Create Secret
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/deploy ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          sudo -s
          echo ${{ secrets.TOKEN }} > /usr/secure/.token
          ENDSSH

      - name: Create Secret
        run: |
            ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/deploy ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
            sudo -s
            echo ${{ secrets.TOKEN }} > /usr/secure/.token
            ENDSSH